//mgbaird
#ifndef TYPE_H
#define TYPE_H

#include <stdio.h>
typedef enum type {
    AND,
    ARRAY,
    ARRAY_ACCESS,
    ASSIGN,
    BODY,
    CASE,
    CLOSE_BRACE,
    CLOSE_BRACKET,
    CLOSE_PAREN,
    CLOSURE,
    COLON,
    COMMA,
    CURLY_BRACES,
    DEFINE,
    DIVIDED_BY,
    ELSE,
    END_DEFINE,
    END_OF_INPUT,
    ENV,
    EQUALS,
    EXPONENT,
    FALSE,
    TRUE,
    FUNCTION_CALL,
    GREATER_THAN,
    GREATER_THAN_OR_EQUALS,
    IF,
    INTEGER,
    LAMBDA,
    LESS_THAN,
    LESS_THAN_OR_EQUALS,
    LINK,
    MINUS,
    MOD,
    NIL,
    NOT,
    NOT_EQUALS,
    OPEN_BRACE,
    OPEN_BRACKET,
    OPEN_PAREN,
    OR,
    PARENTHESIS,
    PLUS,
    QUESTION_MARK,
    REAL,
    REMAINDER,
    RETURN,
    SEMICOLON,
    STRING,
    TABLE,
    THIS,
    TIMES,
    UNARY_MINUS,
    UNARY_PLUS,
    UNINITIALIZED,
    UNKNOWN,
    VARIABLE,
    VERTICAL_BAR,
    WHILE,
    WHILE_SPLIT,
    BUILTIN,
    FILE_POINTER

} Type;

char* typeToString(Type type);

#endif